- client/scripts/components/basics/Directions.js
- client/scripts/index.js
- src/index.js
Adds support for [DirectionsRenderer](https://developers.google.com/maps/documentation/javascript/directions#DisplayingResults). 
I added an example to show how it's used. 
Not sure if I followed the PR guidelines correctly, so let me know if anything needs to be modified.
> Direction renderer

- client/scripts/components/basics/Geolocation.js
- lib/__tests__/index-test.js
- lib/index.js
- package.json
- src/__tests__/index-test.js
- src/index.js
This PR adds support for `<Circle />`. I also updated the geolocation example to show a circle around the coords. Hope I've done the things right with this conventional changelog and build etc. :-)
> Add support for Circle

- lib/Marker.js
- src/Marker.js
Something bad would happen when you try to use children inside `noscript` tag.
> Fix usage of noscript

- client/scripts/components/GeojsonToComponents.js
- client/scripts/components/GettingStarted.js
- client/scripts/components/basics/AsynchronousLoading.js
- client/scripts/components/basics/Directions.js
- client/scripts/components/basics/Geolocation.js
- client/scripts/components/basics/SimpleMap.js
- client/scripts/components/events/AccessingArguments.js
- client/scripts/components/events/ClosureListeners.js
- client/scripts/components/events/GettingProperties.js
- client/scripts/components/events/SimpleClickEvent.js
- src/GoogleMaps.js
- src/internals/VirtualContainer.js
We don't need leaky `mapProps` on `GoogleMaps` component anymore! hooray!
> Feature render to virtual container

- examples/gh-pages/webpack.config.js
- src/GoogleMaps.js
- src/internals/EventComponent.js
- src/internals/SimpleChildComponent.js
Thanks @wuct to point this out.
> Fix components blinking issue

- examples/gh-pages/scripts/ReactRoot.js
- examples/gh-pages/scripts/components/drawing/DrawingTools.js
- examples/gh-pages/scripts/html.js
- lib/DrawingManager.js
- lib/index.js
- lib/internals/SimpleChildComponent.js
- package.json
- src/DrawingManager.js
- src/index.js
- src/internals/SimpleChildComponent.js
Resolves #28 and exposes DrawingManager as `require("react-google-maps").DrawingManager`
> Support for Drawing API

- .travis.yml
- examples/gh-pages/IsomorphicReactPluginFactory.js
- examples/gh-pages/package.json
- examples/gh-pages/scripts/ReactRoot.js
- examples/gh-pages/styles/_bootstrap_override.scss
- examples/gh-pages/styles/_bootstrap_variables.scss
- examples/gh-pages/styles/index.scss
- examples/gh-pages/webpack.config.js
> Chore node 012 compatibility

- examples/gh-pages/scripts/ReactRoot.js
- examples/gh-pages/scripts/components/basics/StyledMap.js
- package.json
- src/addons/InfoBox.js
> Support for InfoBox

- examples/gh-pages/scripts/ReactRoot.js
- examples/gh-pages/scripts/components/basics/OverlayView.js
- src/OverlayView.js
- src/index.js
- src/internals/createOverlayViewProxy.js
> Feat petebrowne add overlay view

- README.md
- docker-compose.yml
- examples/gh-pages/Dockerfile
- examples/gh-pages/package.json
- examples/gh-pages/webpack.config.js
> Chore docker

- README.md
- examples/gh-pages/package.json
- package.json
[tomchentw-npm-dev@v2.0.0](https://github.com/tomchentw/tomchentw-npm-dev/releases/tag/v2.0.0)
> Chore upgrade tomchentw npm dev

- examples/gh-pages/scripts/components/basics/KmlLayer.js
- examples/gh-pages/scripts/constants/Actions.js
- src/KmlLayer.js
- src/creators/KmlLayerCreator.js
- src/eventLists/KmlLayerEventList.js
- src/index.js
@tomchentw I have addressed the feedback you provided on my last pull request:
1. Please don't compile lib in the commits. We'll do this with release scripts
*No lib changes are included in this pull request*
2. Please change the first commit message to: feat(KmlLayer): add new KmlLayer component
*Done*
3. Please change the second commit message to: docs(gh-pages): add KmlLayer example
*Done*
Please let me know if there are any further changes you would like me to make before this pull request is ready to merge.
> KmlLayer support

- README.md
There is no actual different between windows and mac now (thanks cross-env).
> docs(README.md): merge mac & windows dev steps

- README.md
https://github.com/tomchentw/react-google-maps/issues/275 lot of people confused about this
> Added Loading Libraries section

- README.md
Reverts tomchentw/react-google-maps#284
> Revert "Added Loading Libraries section"

- README.md
The examples when tried to run is throwing errors. Had to explicitly import the components, else it will throw errors. Although this is obvious with experienced react developers this is not the case for beginners.
> Updated Examples to make it work out of the box.

- src/lib/addons/MarkerClusterer.js
> add batchSize option

- src/lib/enhanceElement.js
> fix Google Maps exception when passing undefined callbacks #530

- src/lib/async/withScriptjs.js
AFAIK the wording of the comment is wrong.
> Fix incorrect comment

- public/index.html
- src/app/App.js
- src/app/containers/Application.js
- src/app/pages/addons/MarkerWithLabelExample.js
- src/app/pages/addons/index.js
- src/app/pages/addons/markerWithLabel.css
- src/lib/Marker.js
> MarkerWithLabel utility support for custom pins

- README.md
As I was using this package, I was confused as to how to set the position of my `Marker` component. I had to dig into the source code to find that `Marker` receives a list of uncontrolled props that matches the list here: https://developers.google.com/maps/documentation/javascript/3.exp/reference#Marker
I simply updated the `Marker` docs to link to the Google reference. Please let me know if there is a better way you'd like me to do this.
> Update documentation for Marker

- package.json
Allow `react@15.6.1` to be used.
> Relax peerDependencies

- .travis.yml
> CI - build src files from macros before running tests

- src/components/GoogleMap.md
The import file name should be anchor instead of ancho.
https://conventionalcommits.org/
> Fix the import filename

- types/index.d.ts
> Fix TypeScript definitions draggable property type

- types/index.d.ts
- Added missing prop types to OverlayViewProps
- Added type definitions for OverlayView static properties
closes #738
> fix(types): fix OverlayView type definition
