tomchentw/react-google-maps

examples/gh-pages/package.json
webpack-dev-server bind localhost default.
but docker use 0.0.0.0:8080
so change webpack-dev-server to bind 0.0.0.0 will fix the problem.
=> chore(examples): update webpack-dev-server to bind 0.0.0.0

examples/gh-pages/scripts/components/GettingStarted.js, src/internals/SimpleChildComponent.js
Currently a markers animation runs on every state change, this patch makes sure to only set the animation on the initial run.
=> Marker animation fix

src/GoogleMaps.js, src/internals/VirtualContainer.js
=> Fix render virtual container same lifecycle

src/GoogleMaps.js
* Thanks to @petebrowne
* Original commit: a4b48a1307c4dcd2206c4b288521174f81d2bea7
* Closes #64
=> feat(GoogleMaps): specify map bounds via declarative props.bounds

examples/gh-pages/scripts/components/AsyncGettingStarted.js, src/async/ScriptjsGoogleMap.js, src/async/ScriptjsLoader.js
This is a rewrite based on issue of #145 . Could @mattjstar please help review this? Thanks!
=> feat(async/ScriptjsLoader): rename from async/ScriptjsGoogleMap

examples/gh-pages/scripts/components/AsyncGettingStarted.js, examples/gh-pages/scripts/components/GettingStarted.js, src/GoogleMap.js, src/GoogleMapLoader.js, src/async/ScriptjsLoader.js, src/index.js
Use `GoogleMapLoader` with `props.googleMapElement` instead
We also suggest switching to [callback based ref](https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute) so that you'll get the component instance when it is mounted.
Before:
```js
<GoogleMap containerProps={{
...this.props,
style: {
height: "100%",
},
}}
ref="map"
defaultZoom={3}
defaultCenter={{lat: -25.363882, lng: 131.044922}}
onClick={::this.handleMapClick}>
{this.state.markers.map((marker, index) => {
return (
<Marker
{...marker}
onRightclick={this.handleMarkerRightclick.bind(this, index)} />
);
})}
</GoogleMap>
```
After:
```js
<GoogleMapLoader
containerElement={
<div
{...this.props}
style={{
height: "100%",
}}
/>
}
googleMapElement={
<GoogleMap
ref={(map) => console.log(map)} …
```
=> refactor(GoogleMapLoader): introduce loader component interface

package.json, src/__tests__/GoogleMap.spec.js, src/creators/GoogleMapHolder.js
To start rendering `<GoogleMap>`, put it in the props of the `<GoogleMapLoader>` element. Make sure to add <script src="https://maps.googleapis.com/maps/api/js"></script> to your <head> tag to provide google.maps reference
```js
import { GoogleMapLoader } from "react-google-maps";
<GoogleMapLoader
containerElement={<div/>}
googleMapElement={
<GoogleMap
defaultZoom={3}
defaultCenter={{lat: -25.363882, lng: 131.044922}}
>
<Marker {...this.props.markerProps} />
</GoogleMap>
}
/>
```
You can also use `<ScriptjsLoader>` introduced in [v4.6.0](https://github.com/tomchentw/react-google-maps/releases/tag/v4.6.0) to load the Google Maps JavaScript API v3 for you.
```js
import {default as FaSpinner} from "react-icons/lib/fa/spinner";
import {default as ScriptjsLoader} from …
```
=> feat(GoogleMap): add warning for undefined google object

lib/creators/OverlayViewCreator.js, src/creators/OverlayViewCreator.js
Sometimes, the width & height reported to the `getPixelPositionOffset` function are stale (from a previous render). This moves the `_positionContainerElement` method to the callback of the `ReactDOM.render` method to ensure React is done rendering before positioning the container.
=> fix(OverlayViewCreator): position container after render

examples/gh-pages/src/containers/Application.js, examples/gh-pages/src/pages/basics/PopUpInfoWindow.js, examples/gh-pages/src/pages/basics/index.js, examples/gh-pages/src/views/routes.js
Added an example for nested InfoWindows for gh-pages.
A separate page apart from 'Using closures in event listeners' example to glean information about InfoWindow being able to nest components would help new users adopt react-google-maps more easily. Further, the InfoWindow is a vital component to react-google-map's usability, and thus should be prominently exemplified.
=> docs(gh-pages): add Pop-up InfoWindow nesting example

README.md
I may be missing something, but from what I could tell, the SimpleMap code example listed in the README file is not actually valid code... I was unable to get it working without bind() errors. It also heavily uses the 'this' keyword and .bind() despite being defined as a pure (stateless) functional component, which is uncommon and a little confusing (especially if someone were to define it using an arrow function without understanding how it differs).
I updated it to be more like the sample SimpleMap linked here: 
https://github.com/tomchentw/react-google-maps_examples_simple-map/blob/493c95b5830a36434d648b9d7f779f231d2c79a5/src/scripts/SimpleMap.js
For now, I replaced the {...props} spread in GoogleMapLoader with {...props.containerElementProps}, as the click handlers are now being …
=> Update SimpleMap Component Example in README.md

package.json
Recently fixed the broken image urls in one of the dependencies, this PR just bumps the dep version so it's fixed in react-google-maps.
https://github.com/mikesaidani/marker-clusterer-plus/pull/2
This will fail builds until @mikesaidani merges https://github.com/mikesaidani/marker-clusterer-plus/pull/3 (which bumps the package version on his side so that recent changes can be installed via npm).
=> Fix #255 by bumping marker-clusterer-plus dependency to 2.1.3

src/creators/OverlayViewCreator.js
Since `OverlayView` can represent any kind of overlay, including extremely
custom markers, it makes sense to allow it to be clustered. For this to work,
we only have to implement two functions of the `Marker` class: `getDraggable`
and `getPosition`.
The `MarkerClusterer` will call our `OverlayView`'s `setVisible` method as
needed.
=> Let `OverlayView` be clusterd in `MarkerClusterer`

README.md
Okey, i did a mess @jmagrippis i reverted the last commit to avoid any issue. This is safe now.
=> Cristiandley readme libraries section

src/OverlayView.js
Fix for #301. Same approach as in https://github.com/tomchentw/react-google-maps/blob/master/src/Marker.js#L98.
=> fix(overlay-view): fixed bug in OverlayView when nested in MarkerClusterer

src/async/ScriptjsLoader.js
Make the callback from scriptjs a no-op when unmounting the component.
There was a corner case where the component would be unmounted while scriptjs was doing its thing. The callback would then call setState, thus triggering a warning from React.
=> fix(ScriptjsLoader): Fix setState warning

README.md
This PR fixes the typo on the README. `hensitate` => `hesitate`
=> Fix #355 - Fix typo on README.MD

src/lib/InfoWindow.js, src/lib/addons/InfoBox.js, src/lib/enhanceElement.js
Now in `InfoWindow` or `InfoBox` children you can use components like React Router's `Link`, which relies on React context for route matching information. Addresses #258.
ETA: For this to work all prop updater functions from a component's `controlledPropUpdaterMap` are called from `enhanceElement` with a supplied `this` (via `Function.prototype.call`). See [here](https://github.com/tomchentw/react-google-maps/pull/361/files#diff-8b3b61db2ea6af52ddd66b61ca5494ffR90). This wasn't necessary before since none of the updaters required `this`, but we need `this` in order to get React context.
=> fix(info-context): InfoBox/InfoWindow children receive React context (addresses #258)

src/lib/addons/InfoBox.js
Hi, 
I want to address an obscure issue that arises from failing to clean up InfoBox listeners on unmount. Taking a look at the end of the file here: https://github.com/googlemaps/v3-utility-library/blob/master/infobox/src/infobox.js it seems there's more to do than simple `setMap(null)` in order to remove `InfoBox` from the map. In particular, all the listeners should be cleaned up. Perhaps calling `infoBox.close()` on unmounting makes more sense here?
=> Unmounting an InfoBox removes all listeners.

src/lib/HeatmapLayer.js
HeatmapLayer should use google.maps.visualization.HeatmapLayer() as the constructor. See here for more information: https://developers.google.com/maps/documentation/javascript/3.exp/reference#HeatmapLayer.
#375
=> fix(HeatmapLayer): HeatmapLayer constructor fix

src/lib/addons/InfoBox.js
The old link is defunkt, this new documentation link seems appropriate.
=> Updating documentation link for GoogleMapsInfobox.

src/app/pages/places/SearchBoxExample.js
When implementing maps with searchbox for my project, I faced the problem with map not auto-zooming on searched places. Say if I have a default zoom of 10 over my town, but when I search for a specific place, map keeps zoom at 10 which didn't work for me. 
Therefore, I have added new bounds for the searched places within handlePlacesChanged() handler and forced the map to zoom in with fitBounds(bounds)
I didn't find this solution in any FAQ thread, so thought it might be useful. Thanks for your project and forgive if I submitted this change incorrectly - I'm a git newbie!
=> Added the availability to auto-zoom on places

src/macros/GoogleMap.jsx
This change allows users to access the [`mapTypes.set`](https://developers.google.com/maps/documentation/javascript/3.exp/reference#MapTypeRegistry) property without using the secret context property.
Adds a new method `map.addMapType` - let me know if this isn't close enough to the Google Maps API - something like `map.mapTypesSet` might me more inline with API reference.
Allow a map style to only apply to one map type. Below, I'm replacing the road map with custom styles and leaving the satellite view as default.
```js
import React from 'react';
import { GoogleMap, withGoogleMap, withScriptjs } from 'react-google-maps';
import mapStyles from './mapStyles';
const Map = withScriptjs(withGoogleMap(props => {
const handleMapLoad = map => {
if(map) {
const styledRoadmap = new …
```
=> Added function to access MapTypeRegistry

src/macros/places/SearchBox.jsx
This tiny change allows having other elements around `input` when defining `<SearchBox />`:
```js
<SearchBox>
<div className={styles.searchBox}>
<input className={styles.searchInput} type="text" />
{isSearching && (
<button className={styles.clearSearchButton} type="button" onClick={this.clearSearch}>
Clear
</button>
)}
</div>
</SearchBox>
```
=> feat(places/SearchBox): allow other elements around SearchBox input

src/macros/InfoWindow.jsx
`6a61f2c` updated `InfoWindow` to support React@^16.
Unfortunately, prior to this commit, when re-rendering is
triggered from the parent (e.g. due to a state change) without
requiring re-mounting, the following error is returned:
Invariant Violation Target container is not a DOM element
The above error was caused by `this.containerElement` being set
to undefined after the component mounts. Consequently, when
`render()` is called again, it would fail. If we are always
re-mounting the `InfoWindow` component, the aforementioned error
will not occur.
For example:
```
<Marker position={{ lat: -34.397, lng: 150.644 }}>
{showInfoWindow ? (<InfoWindow>
<div>Hello World!</div>
</InfoWindow>) : null}
</Marker>
```
The above code will result in `InfoWindow` re-mounting when
re-rendering (e.g. when …
=> fix(InfoWindow): do not remove container element on mount

src/macros/places/StandaloneSearchBox.jsx
`StandaloneSearchBox` searches for an input element inside itself to pass to `google.maps.places.SearchBox`. If no such element is found it defaults to itself.
Closes #708
=> feat(StandaloneSearchBox): Accept wrapped input

src/macros/places/SearchBox.jsx
Google Maps Api error can cause removal of searchBox which can results into an error at unmount while trying to append undefined to containerElement
=> fix(places/SearchBox): undefined child at unmount
